language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install -r dev_requirements.txt
before_script:
- git config --global user.name "Travis"
- git config --global user.email "travis@example.com"
script:
- nosetests
- flake8 maintain tests --ignore=E501 --exclude=tests/release/fixtures
